### ISSUE TITLE
Ligue de la compétition

### ISSUE THREAD

**Issue by Kirscher** [Kirscher/ResultAthle#1]
corriger l'erreur si ligue contient plus de 3 caractères (ex: ARRAS)

**Comment by Yzeghal** [comment]
Attention, j'ai l'impression que le scrap de la ligue pour Guillaume Petras (rang n°12) est allé chercher sa catégorie SEM plutot que sa ligue (il n'en a pas). 
Il faudrait trouver quelque chose qui discrimine la ligue de la catégorie dans tous les cas (l'un ou l'autre vide)

**Comment by Kirscher** [comment]
En fait j'avais déjà fait un test pour voir si la ligue scrapée était dans le dictionnaire des catégories
Il y avait juste un problème avec la catégorie espoir (ESM et ESF)
C'est corrigé 👍
