### ISSUE TITLE
Renommage automatique de l'output csv 

### ISSUE THREAD

**Issue by Kirscher** [Kirscher/ResultAthle#19]
le fichier téléchargé en en csv ou excel doit porter le nom de la compétition

**Comment by Kirscher** [comment]
à récupérer dans les infos du header, facile

**Comment by AntoineTSP** [comment]
C'est chose faite par ce code:
title = f"<div style='text-align: center; font-weight: bold; font-size: 30px;'>Competition: {header['nom']}</div>"
show(data, buttons = ['copy',{
                'extend': 'csv',
                'filename': header['nom'],
                'text': 'Download CSV'},
                {'extend': 'excel',
                'filename': header['nom'],
                'text': 'Download Excel'},
                {'extend': 'pdf',
                'filename': header['nom'],
                'text': 'Download PDF'}],
                max_rows=100, tags=title)
