### ISSUE TITLE
Forcer le paging (plutôt qu'afficher toute la table) avec shiny

### ISSUE THREAD

**Issue by AntoineTSP** [Kirscher/ResultAthle#35]
Ce code:
import itables.options as opt
opt.maxBytes = 10000
show(data, buttons = ['copy',{
                'extend': 'csv',
                'filename': header['nom'],
                'text': 'Download CSV'},
                {'extend': 'excel',
                'filename': header['nom'],
                'text': 'Download Excel'},
                {'extend': 'pdf',
                'filename': header['nom'],
                'text': 'Download PDF'}],
                tags=title, lengthMenu=[2, 5, 10, 20, 50])

compresse la table (d'autant plus maxBytes est grand) mais la plot totalement contrairement avec simplement itables.

**Comment by Kirscher** [comment]
Issue résolue en affichant uniquement les colonnes d'intérêt dans les résultats et non celles pour les analyses stats (time_delta, duration (s), etc.)
