### ISSUE TITLE
Error in processing timeseries data in your pipeline

### ISSUE THREAD

**Issue by linogaliana** [Kirscher/ResultAthle#40]
I was trying to run your `main.ipynb` file using `Quarto`. I encountered the following error, probably because one of the pages have changed since you ran your pipeline. It comes from this cell:

```python
header, data = scraping.get_results("https://bases.athle.fr/asp.net/liste.aspx?frmbase=resultats&frmmode=1&frmespace=0&frmcompetition=282742", 13)
```

![image](https://github.com/Kirscher/ResultAthle/assets/33896139/40525d07-4be1-4265-9ced-5baa75f9f6e1)

Looking at `utils/scraping.py`, I found the error comes from there:

```python
data["hours"] = data["Chrono"].dt.hour
data["minutes"] = data["Chrono"].dt.minute
data["seconds"] = data["Chrono"].dt.second
```

Which I  identified as coming from the first row of your dataset where html parsing did not end well:
   
![image](https://github.com/Kirscher/ResultAthle/assets/33896139/e0948539-15f8-4cf5-b362-86979293b63f)

Is it possible for you to fix that problem ?

**Comment by Kirscher** [comment]
The results page has indeed changed, with the organizers adding a new line for performance points counts. I hadn't seen this in previous pages, which might be because this race is international. As a result, the current scraping script isn't robust enough to handle these changes.

![image](https://github.com/Kirscher/ResultAthle/assets/85068746/c9d019c7-788d-4b62-9b86-a6d109b29e65)

I am working on it to fix it

**Comment by linogaliana** [comment]
If you have a page that you know is working well, it is ok to me. I know webscraping can be unstable and its hard to prevent problems in such pipeline.

What I want to do is see your quarto output, which should work fine if you propose me a page that is not generating this bug

**Comment by Kirscher** [comment]
The provided result page should now work properly. This update also covers standard events such as 5K, 10K, half marathons, and marathons. However, for more complex meetings that include multiple competitions race formats and types like throws and hurdles, there may still be some issues with robustness.

**Comment by linogaliana** [comment]
Thanks for the quick action, I have been able to reproduce your app. You can close the issue
